language: node_js
sudo: required
addons:
  chrome: stable
node_js:
  - '8.9'

branches:
  only:
    - master

install:
  - npm install

before_script:
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
script:
  - npm run lint
  - npm run test
  - npm run e2e
