language: node_js
sudo: required
dist: trusty
node_js:
  - '8.9'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - google-chrome
    packages:
      - google-chrome-stable
      - lib32stdc++6
      - lib32z1
branches:
  only:
    - master
install:
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run lint
  - npm run test
  - npm run e2e
