language: node_js
sudo: required
dist: trusty
node_js:
- '8.9'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - google-chrome
    packages:
    - google-chrome-stable
    - lib32stdc++6
    - lib32z1
branches:
  only:
  - master
install:
- npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run lint
- npm run test
env:
  global:
    secure: kArQQt1D8XH45KSjLVRN56i7TQE7RRMdJ8NKxlt2g6TAU4s7Nmwd72mU7IrP/Q04AAfQwD7JVD/zt7vSDHsLErmob2kX/oBLqCpGbiNo2gOLwRSMEg7qEjbGfCywSQ1KSdfGA87TgYW5qYRRWiXBFk+s2ANk2My1RHkgMF7S1rTkgiH5Z2Wa0oTSngE/ScA00lZBj4rqrdOTkhM9SKEkmrogJH2Z87Ela9gjbRDp+ktXxCwWNEMg66CIGHad61X/rFBhfabpC2njgS16m3/2EB2t6x4GQo5q9qQgquLFMX4fF+lJPu6R2QrKFd+W2otUGFp28xXHIga4irY6i6PKb+YkNysSYHFEfVStxKzP/DDnwNII5jzPPZSdxlGLzo6CrK/8EcDZR/1p4H9dwlk0ITRzh1zJSFFxboiKgtlHlo7l7z9GtgLMwyG5e/mrB2Q3H1xOSQM6iNtBRYtqTNHxdpeg6Ouucy7pbu9czeTT30o7qBle+ICINDzv03iTUW7cza9L9SNYszBJco3evmsT2kWIQ5DvQDqS8Bb7YaOp38mBy4mq5s6QBhPNlLeBW88BPje321Iwa9t+HHM64opVdRglE5WIloKEjID3D/cLjrVNHWJRdD9hB4/djFvW7tz6o3WJhMxpMX5b5gzTV77DgJHQ4I2x9+Ma/WpAPovhF6k=
